### ISSUE TITLE
Skynet blocking GitHub access by "forgetting" existing whitelist entry

### ISSUE THREAD

**Issue by TheStork239** [Adamm00/IPSet_ASUS#77]
###### Brief Description Of Issue
Every few days Skynet blocks access to Github.com (e.g. IP 140.82.121.3) due to Github IPs erroneously ending on an IP block list, but somehow the existing whitelisting of that IP does not get checked or executed by Skynet.

Logs contain blocks of e.g. 140.82.121.3, but when trying to add that IP to the whitelist Skynet notifies that it has already been added.

Therefore it seems like Skynet is somehow missing putting the whitelist entries for GitHub into action.

(I am not the only one with the issue; there seems to be a number of people with this issue on discussion forums)
I am using an RT-AC88U router with Merlin 386.3_2 firmware, with Diversion running in addition to Skynet.

###### Steps To Reproduce Issue
Seems to occur randomly every few days.  Issue seems to be temporarily fixed by either 1) disabling Skynet off, 2) manually refreshing whitelist entries, or 3) rebooting router.  However, that is only a temporary fix and the issue seems to recur.

###### Expected Behaviour
Github.com and related IPs are already on the built-in Skynet whitelist, so access to GitHub.com should not be blocked by Skynet.

###### Output of ( sh /jffs/scripts/firewall debug info )
![image1](https://user-images.githubusercontent.com/80922293/133928616-551f7ee3-8781-45d2-8b74-2f2eb38d4fb9.jpeg)
![image0](https://user-images.githubusercontent.com/80922293/133928622-93566675-416a-4aca-befb-67c659732152.jpeg)

**Comment by Adamm00** [comment]
I had some ideas for whitelist improvements but it got put on the back-burner. This is nothing more then an (annoying) false positive from firehol lvl3. You can temporarily remove this from your filter list. I’ll see about other whitelist improvements when I get a chance.

**Comment by p3yot3** [comment]
Thanks for reporting this issue - I thought it was just me !

**Comment by Adamm00** [comment]
I've pushed v7.2.6 https://github.com/Adamm00/IPSet_ASUS/commit/f0cea071acd30b03af3173fd9dc75e7a21311492

This will add GitHubs asn to Skynet's whitelist to avoid any IP changes. I have plans to make the whitelist more accurate with domains, but it will take some time to implement as my free time is limited. 

As for some of those commenting on SNB, I find it distasteful. I've provided free support and the groundwork for countless addons for 7+ years. Rather then take shots at someone whose not around to defend themselves, create a pull request and remember this is an "open source" project.

**Comment by TheStork239** [comment]
Thank you @Adamm00 ; really appreciate your help and support.  I’ll give this fix a try later on.

**Comment by dave14305** [comment]
> As for some of those commenting on SNB, I find it distasteful. I've provided free support and the groundwork for countless addons for 7+ years. Rather then take shots at someone whose not around to defend themselves, create a pull request and remember this is an "open source" project.

Will do!

**Comment by p3yot3** [comment]
Updated & so far so good. Thanks for all your hard work - it is very much appreciated by most of us!

**Comment by TheStork239** [comment]
Updated and seems to do the trick.  Thanks!  I’ll close the issue.

**Comment by entrop1x** [comment]
I've updated Skynet to v7.2.6 and the 140.82.121.3 ip still ends up getting blocked.
![githubblock](https://user-images.githubusercontent.com/66232261/134792028-144160de-e52a-4dfa-9ef0-054b185155f4.png)

I had to add it to Whitelist, but even I don't know how long that'll work. 
I think this issue should remain open.

**Comment by TheStork239** [comment]
Ok. I’ll re-open the issue as it still seems to be causing trouble for some.

**Comment by TheStork239** [comment]
I can confirm that even with v7.2.6 GitHub.com does from time to time still get blocked.  It seems to be fixed (temporarily) with a manual refresh of entries in the whitelist, through Skynet command line.  It appears as if somehow Skynet “forgets” the whitelist until the entries are refreshed.

**Comment by dave14305** [comment]
I believe the problem is some kind of rate limiting by bgpview.io. If you remove the `&` at the end of line 879, it works more reliably, albeit slower.
https://github.com/Adamm00/IPSet_ASUS/blob/f0cea071acd30b03af3173fd9dc75e7a21311492/firewall.sh#L879

**Comment by dave14305** [comment]
`add Skynet-Whitelist 140.82.112.0/20 comment "CDN-Whitelist: Github"`
This should be capturing the 140.82.121.3 address.

**Comment by Adamm00** [comment]
Going to try tackle this again soon. From a quick test it seems a line around 1000 characters (all domains from /jffs/addons/shared-whitelists/* combined) causes dnsmasq to fail.


`Jan 13 21:34:40 Skynet: [i] Restarting Firewall Service
Jan 13 21:34:40 rc_service: service 21463:notify_rc restart_firewall
Jan 13 21:34:40 rc_service: waitting "start_dnsmasq" via watchdog ...
Jan 13 21:34:51 Diversion: auto-added IPv6 entries to blocking list(s) and blacklist, this might have taken some time
Jan 13 21:34:51 Diversion: restarted Dnsmasq to apply settings
Jan 13 21:34:51 stubby[21596]: Stubby version: Stubby 0.4.0
Jan 13 21:34:51 dnsmasq[21598]: bad option at line 56 of /etc/dnsmasq.conf
Jan 13 21:34:51 dnsmasq[21598]: FAILED to start up
Jan 13 21:34:51 custom_script: Running /jffs/scripts/service-event-end (args: start dnsmasq)`


I welcome anyone else to take a look as my free time is very limited recently.

**Comment by dave14305** [comment]
OpenWrt looks like it will go with the equivalent of one domain per line.
https://github.com/openwrt/openwrt/pull/4667

**Comment by decoderman** [comment]
One can add multiple --addn-hosts files to Dnsmasq. Each file I add with Diversion can be 1 or up to 25 domains per line mapped to an IP (it's a user setting in Diversion). In my tests, the maximum number of domains per line is somewhere around 28 before Dnsmasq crashed/complained.
That's for hosts files though, I have no idea what the --ipset option accepts.

I am not even sure you can add multiple --ipset directives, though one would think so as IPv4 and IPv6 entries should be separately added as per the Dnsmasq manpage.

**Comment by Adamm00** [comment]
https://github.com/Adamm00/IPSet_ASUS/commit/7e374be7a133bfb305462e06dcea3eb9f772ca29

For those of you wanting to try this out, there's a new branch to avoid a situation like last time. I'd appreciate any feedback.

**Comment by dave14305** [comment]
> [7e374be](https://github.com/Adamm00/IPSet_ASUS/commit/7e374be7a133bfb305462e06dcea3eb9f772ca29)
> 
> For those of you wanting to try this out, there's a new branch to avoid a situation like last time. I'd appreciate any feedback.

Depending on the number of domains people whitelist, you might consider a timeout on the Skynet-WhitelistDomains set (e.g. 86400), to prevent unnecessary growth as IPs change. And if you go that route, it’s usually a good idea to complement that with max-cache-ttl=86400 in dnsmasq.conf.add. I’m just imagining the worst-case scenario ahead of time.

I like the clever use of xargs! I learn something new every time there’s a new feature added!

**Comment by Adamm00** [comment]
> > [7e374be](https://github.com/Adamm00/IPSet_ASUS/commit/7e374be7a133bfb305462e06dcea3eb9f772ca29)
> > For those of you wanting to try this out, there's a new branch to avoid a situation like last time. I'd appreciate any feedback.
> 
> Depending on the number of domains people whitelist, you might consider a timeout on the Skynet-WhitelistDomains set (e.g. 86400), to prevent unnecessary growth as IPs change. And if you go that route, it’s usually a good idea to complement that with max-cache-ttl=86400 in dnsmasq.conf.add. I’m just imagining the worst-case scenario ahead of time.
> 
> I like the clever use of xargs! I learn something new every time there’s a new feature added!

Yeah I still need to work out a few details in the implementation on how to avoid stale entries and so that entries are removed correctly when the domain is no longer whitelisted. So expect to see that soon once I can confirm the implementation doesn’t break dnsmasq or anything like last time and proves reliable. 

As for xargs, thanks, I still try stay creative… admittedly had to dust off a few bash cobwebs when taking a look.

**Comment by decoderman** [comment]
With a reasonable 139 whitelist entries total (109 in Diversion) my AX88U on 386.4 firmware has a slightly delayed startup time for Dnsmasq. Nothing to worry so far. Thanks for your effort.

**Comment by Adamm00** [comment]
@decoderman 

So while stress testing this solution with 150+ domains in a new testing shard list I kept running into an issue with Diversion. It seems something doesn't sit right and causes diversion to get hung up on processing the blacklist file that swells up to 100MB+ of nonsense preventing DNS from ever starting up until the USB device is removed (or blacklist file deleted). Perhaps something worth looking into on your end?

https://i.imgur.com/FiMxpu5.png
https://i.imgur.com/PkPJNGT.png

**Comment by decoderman** [comment]
Definitely something to look into. I’ve heard of exponential growth of the blacklist before from a user or two.
Are the entries gibberish or just duplicates?

**Comment by Adamm00** [comment]
> Definitely something to look into. I’ve heard of exponential growth of the blacklist before from a user or two. Are the entries gibberish or just duplicates?

https://drive.google.com/file/d/1RxIUsXVwLgfrQEHSnG71BVttBjq3cOqD/view?usp=sharing

Can't open the file in any editor without it crashing.

**Comment by decoderman** [comment]
> Can't open the file in any editor without it crashing.
> 
> EDIT: It finally opened and contains 102,883,329 blank lines lol. I see how the router might crash when trying to process that.

I'll get to it ASAP. Thanks for the evidence.

**Comment by dave14305** [comment]
> [7e374be](https://github.com/Adamm00/IPSet_ASUS/commit/7e374be7a133bfb305462e06dcea3eb9f772ca29)
> 
> For those of you wanting to try this out, there's a new branch to avoid a situation like last time. I'd appreciate any feedback.

I've got v7.3.1 running (mostly due to the latest Cyclops threats). I don't have many Diversion domains whitelisted, so my Skynet-WhitelistDomains ipset entry in dnsmasq.conf.add has mostly the built-in hard-coded domains (e.g. entware.net, githubusercontent.com, etc.).

This made me realize that these hard-coded domains are not likely to get populated in the Whitelist ipset since most of them are resolved on the router and won't ever be queried through dnsmasq, but directly by WAN DNS servers (with default firmware settings for local resolver).

Only domains requested from a LAN client will reach dnsmasq and populate the ipset, which is good, but doesn't help the router's own whitelisted domains. Unless you `nslookup bin.entware.net 127.0.0.1` to prime the ipset, for example.

**Comment by Adamm00** [comment]
Fair point, I do hate the fact we have to go back to cycling domains with nslookup and wish we had something faster like dig built-in, but I think the best middle ground here is just todo hard coded domains and not others. 

Thanks for pointing this out, I do still get notifications when people post on issues etc and read them all so I apologize if I'm slow to reply as I usually wait until I have free time to work on things. Waiting on some legal hurdles on getting an AXE11000 which should be some inspiration to dig back into things. Will try push an update for this soon

**Comment by ToniToneLo** [comment]
Interesting.
